GET http://localhost:3001/api/notes

###

GET http://localhost:3001/api/notes/1 or 1 = 1

###

GET http://localhost:3001/api/notes/4

###

DELETE http://localhost:3001/api/notes/1

###

# Insert a note
POST http://localhost:3001/api/notes
Content-Type: application/json

{
"content": "This is a new note!",
"important": true
}

###

# Insert a wrong note
POST http://localhost:3001/api/notes
Content-Type: application/json

{
"important": true
}